// Generated by CIRCT unknown git version
module CordicPreprocessor(	// <stdin>:3:3
  input  [15:0] io_in_rs1,	// src/main/scala/CordicPreprocessor.scala:34:14
  input  [4:0]  io_in_op,	// src/main/scala/CordicPreprocessor.scala:34:14
  output [15:0] io_out_cordic_x,	// src/main/scala/CordicPreprocessor.scala:34:14
                io_out_cordic_y,	// src/main/scala/CordicPreprocessor.scala:34:14
                io_out_cordic_z,	// src/main/scala/CordicPreprocessor.scala:34:14
  output        io_out_control_rotType,	// src/main/scala/CordicPreprocessor.scala:34:14
                io_out_control_mode,	// src/main/scala/CordicPreprocessor.scala:34:14
  output [4:0]  io_out_control_op,	// src/main/scala/CordicPreprocessor.scala:34:14
  output [3:0]  io_out_control_xOpSpecific,	// src/main/scala/CordicPreprocessor.scala:34:14
                io_out_control_yOpSpecific	// src/main/scala/CordicPreprocessor.scala:34:14
);

  wire [7:0] _GEN = {1'h1, 1'h1, 1'h1, 1'h1, 1'h1, 1'h0, 1'h0, 1'h0};	// src/main/scala/CordicPreprocessor.scala:63:26
  wire [7:0] _GEN_0 = {1'h1, 1'h0, 1'h1, 1'h0, 1'h0, 1'h1, 1'h0, 1'h0};	// src/main/scala/CordicPreprocessor.scala:62:26
  wire       _GEN_1 = io_in_op == 5'h0;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       largerThanPiOver2 = $signed(io_in_rs1) > 16'sh1921;	// src/main/scala/CordicOps.scala:130:37
  wire       smallerThanNegPiOver2 = $signed(io_in_rs1) < -16'sh1921;	// src/main/scala/CordicOps.scala:131:37
  wire       _GEN_2 = io_in_op == 5'h1;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       largerThanPiOver2_2 = $signed(io_in_rs1) > 16'sh1921;	// src/main/scala/CordicOps.scala:130:37, :156:37
  wire       smallerThanNegPiOver2_2 = $signed(io_in_rs1) < -16'sh1921;	// src/main/scala/CordicOps.scala:131:37, :157:37
  wire       _GEN_3 = io_in_op == 5'h2;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       _GEN_4 = io_in_op == 5'h3;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       _GEN_5 = io_in_op == 5'h4;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       _GEN_6 = _GEN_5 | _GEN_4;	// src/main/scala/CordicPreprocessor.scala:49:{19,28}, :53:34
  wire       _GEN_7 = io_in_op == 5'h5;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       _GEN_8 = io_in_op == 5'h6;	// src/main/scala/CordicPreprocessor.scala:49:19
  wire       _GEN_9 = io_in_op == 5'h7;	// src/main/scala/CordicPreprocessor.scala:49:19
  assign io_out_cordic_x =
    _GEN_9
      ? io_in_rs1 + 16'h1000
      : _GEN_8
          ? 16'h1351
          : _GEN_7
              ? 16'h1000
              : _GEN_6 ? 16'h1351 : _GEN_3 ? 16'h1000 : _GEN_2 | _GEN_1 ? 16'h9B2 : 16'h0;	// <stdin>:3:3, src/main/scala/CordicOps.scala:258:23, src/main/scala/CordicPreprocessor.scala:41:30, :49:{19,28}, :53:34
  assign io_out_cordic_y =
    _GEN_9
      ? io_in_rs1 - 16'h1000
      : _GEN_8 ? 16'h1351 : _GEN_7 | ~(_GEN_6 | ~_GEN_3) ? io_in_rs1 : 16'h0;	// <stdin>:3:3, src/main/scala/CordicOps.scala:263:23, src/main/scala/CordicPreprocessor.scala:41:30, :49:{19,28}, :53:34, :54:34
  assign io_out_cordic_z =
    _GEN_9
      ? 16'h0
      : _GEN_8
          ? io_in_rs1
          : _GEN_7
              ? 16'h0
              : _GEN_6
                  ? io_in_rs1
                  : _GEN_3
                      ? 16'h0
                      : _GEN_2
                          ? (largerThanPiOver2_2
                               ? io_in_rs1 - 16'h3243
                               : smallerThanNegPiOver2_2
                                   ? io_in_rs1 + 16'h3243
                                   : io_in_rs1)
                          : _GEN_1
                              ? (largerThanPiOver2
                                   ? io_in_rs1 - 16'h3243
                                   : smallerThanNegPiOver2
                                       ? io_in_rs1 + 16'h3243
                                       : io_in_rs1)
                              : 16'h0;	// <stdin>:3:3, src/main/scala/CordicOps.scala:130:37, :131:37, :139:{51,98}, :156:37, :157:37, :166:{51,98}, src/main/scala/CordicPreprocessor.scala:41:30, :43:30, :49:{19,28}, :53:34, :55:34, src/main/scala/chisel3/util/Mux.scala:141:16
  assign io_out_control_rotType = _GEN[io_in_op[2:0]];	// <stdin>:3:3, :128:35, src/main/scala/CordicPreprocessor.scala:63:26
  assign io_out_control_mode = _GEN_0[io_in_op[2:0]];	// <stdin>:3:3, :128:35, src/main/scala/CordicPreprocessor.scala:62:26
  assign io_out_control_op = io_in_op;	// <stdin>:3:3
  assign io_out_control_xOpSpecific =
    _GEN_9 | _GEN_8 | _GEN_7 | _GEN_5 | _GEN_4 | _GEN_3 | ~_GEN_2
      ? 4'h0
      : {2'h0, largerThanPiOver2_2, smallerThanNegPiOver2_2};	// <stdin>:3:3, src/main/scala/CordicOps.scala:156:37, :157:37, src/main/scala/CordicPreprocessor.scala:44:30, :49:{19,28}, :56:34, :57:34
  assign io_out_control_yOpSpecific =
    _GEN_9 | _GEN_8 | _GEN_7 | _GEN_5 | _GEN_4 | _GEN_3 | _GEN_2 | ~_GEN_1
      ? 4'h0
      : {2'h0, largerThanPiOver2, smallerThanNegPiOver2};	// <stdin>:3:3, src/main/scala/CordicOps.scala:130:37, :131:37, src/main/scala/CordicPreprocessor.scala:44:30, :49:{19,28}, :57:34
endmodule

module CordicPostprocessor(	// <stdin>:134:3
  input  [15:0] io_in_cordic_x,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_in_cordic_y,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_in_cordic_z,	// src/main/scala/CordicPostprocessor.scala:32:14
  input  [4:0]  io_in_control_op,	// src/main/scala/CordicPostprocessor.scala:32:14
  input  [3:0]  io_in_control_xOpSpecific,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_in_control_yOpSpecific,	// src/main/scala/CordicPostprocessor.scala:32:14
  output [15:0] io_out_cordic_x,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_out_cordic_y,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_out_cordic_z,	// src/main/scala/CordicPostprocessor.scala:32:14
                io_out_dOut	// src/main/scala/CordicPostprocessor.scala:32:14
);

  wire        _GEN = io_in_control_op == 5'h0;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire [15:0] _GEN_0 =
    _GEN
      ? (io_in_control_yOpSpecific[0] | io_in_control_yOpSpecific[1]
           ? ~io_in_cordic_y + 16'h1
           : io_in_cordic_y)
      : 16'h0;	// src/main/scala/CordicOps.scala:144:{8,16,20,30,35,41}, src/main/scala/CordicPostprocessor.scala:36:39, :40:{27,36}, :45:23
  wire        _GEN_1 = io_in_control_op == 5'h1;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire [15:0] xPostProcess =
    io_in_control_xOpSpecific[0] | io_in_control_xOpSpecific[1]
      ? ~io_in_cordic_x + 16'h1
      : io_in_cordic_x;	// src/main/scala/CordicOps.scala:144:41, :171:{8,16,20,30,35,41}
  wire        _GEN_2 = io_in_control_op == 5'h2;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire        _GEN_3 = io_in_control_op == 5'h3;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire        _GEN_4 = io_in_control_op == 5'h4;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire        _GEN_5 = io_in_control_op == 5'h5;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire        _GEN_6 = io_in_control_op == 5'h6;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire        _GEN_7 = io_in_control_op == 5'h7;	// src/main/scala/CordicPostprocessor.scala:40:27
  wire [15:0] _GEN_8 = {io_in_cordic_z[14:0], 1'h0};	// src/main/scala/CordicOps.scala:268:10, src/main/scala/CordicPostprocessor.scala:46:23
  assign io_out_cordic_x =
    _GEN_7 | _GEN_6 | _GEN_5 | _GEN_4 | _GEN_3 | _GEN_2
      ? io_in_cordic_x
      : _GEN_1 ? xPostProcess : _GEN ? io_in_cordic_x : 16'h0;	// <stdin>:134:3, src/main/scala/CordicOps.scala:171:8, src/main/scala/CordicPostprocessor.scala:36:39, :40:{27,36}, :44:23
  assign io_out_cordic_y =
    _GEN_7 | _GEN_6 | _GEN_5 | _GEN_4 | _GEN_3 | _GEN_2 | _GEN_1
      ? io_in_cordic_y
      : _GEN_0;	// <stdin>:134:3, src/main/scala/CordicPostprocessor.scala:36:39, :40:{27,36}, :45:23
  assign io_out_cordic_z =
    _GEN_7
      ? _GEN_8
      : _GEN_6 | _GEN_5 | _GEN_4 | _GEN_3 | _GEN_2 | _GEN_1 | _GEN
          ? io_in_cordic_z
          : 16'h0;	// <stdin>:134:3, src/main/scala/CordicPostprocessor.scala:36:39, :40:{27,36}, :46:23
  assign io_out_dOut =
    _GEN_7
      ? _GEN_8
      : _GEN_6
          ? io_in_cordic_x
          : _GEN_5
              ? io_in_cordic_z
              : _GEN_4
                  ? io_in_cordic_x
                  : _GEN_3
                      ? io_in_cordic_y
                      : _GEN_2 ? io_in_cordic_z : _GEN_1 ? xPostProcess : _GEN_0;	// <stdin>:134:3, src/main/scala/CordicOps.scala:171:8, src/main/scala/CordicPostprocessor.scala:36:39, :40:{27,36}, :45:23, :46:23, :47:19
endmodule

module AdderSubtractor(	// <stdin>:212:3, :448:3, :684:3, :920:3, :1156:3, :1392:3, :1628:3, :1864:3, :2100:3, :2336:3, :2572:3, :2808:3, :3044:3, :3280:3, :3516:3, :3752:3, :3988:3, :4224:3, :4460:3, :4696:3, :4932:3, :5168:3, :5404:3, :5640:3, :5876:3, :6112:3, :6348:3, :6584:3, :6820:3, :7056:3, :7292:3, :7528:3, :7764:3, :8000:3, :8236:3, :8472:3, :8708:3, :8944:3, :9180:3, :9416:3, :9652:3, :9888:3, :10124:3, :10360:3, :10596:3, :10832:3, :11068:3, :11304:3
  input  [15:0] io_A,	// src/main/scala/AdderSubtractor.scala:26:17
                io_B,	// src/main/scala/AdderSubtractor.scala:26:17
  input         io_D,	// src/main/scala/AdderSubtractor.scala:26:17
  output [15:0] io_S	// src/main/scala/AdderSubtractor.scala:26:17
);

  wire b = io_B[0] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_1 = b & io_A[0] | io_D & (b ^ io_A[0]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_1 = io_B[1] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_2 = b_1 & io_A[1] | C_vec_1 & (b_1 ^ io_A[1]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_2 = io_B[2] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_3 = b_2 & io_A[2] | C_vec_2 & (b_2 ^ io_A[2]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_3 = io_B[3] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_4 = b_3 & io_A[3] | C_vec_3 & (b_3 ^ io_A[3]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_4 = io_B[4] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_5 = b_4 & io_A[4] | C_vec_4 & (b_4 ^ io_A[4]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_5 = io_B[5] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_6 = b_5 & io_A[5] | C_vec_5 & (b_5 ^ io_A[5]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_6 = io_B[6] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_7 = b_6 & io_A[6] | C_vec_6 & (b_6 ^ io_A[6]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_7 = io_B[7] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_8 = b_7 & io_A[7] | C_vec_7 & (b_7 ^ io_A[7]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_8 = io_B[8] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_9 = b_8 & io_A[8] | C_vec_8 & (b_8 ^ io_A[8]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_9 = io_B[9] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_10 = b_9 & io_A[9] | C_vec_9 & (b_9 ^ io_A[9]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_10 = io_B[10] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_11 = b_10 & io_A[10] | C_vec_10 & (b_10 ^ io_A[10]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_11 = io_B[11] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_12 = b_11 & io_A[11] | C_vec_11 & (b_11 ^ io_A[11]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_12 = io_B[12] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_13 = b_12 & io_A[12] | C_vec_12 & (b_12 ^ io_A[12]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_13 = io_B[13] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  wire C_vec_14 = b_13 & io_A[13] | C_vec_13 & (b_13 ^ io_A[13]);	// src/main/scala/AdderSubtractor.scala:33:21, :34:29, :35:{24,35,47,52}
  wire b_14 = io_B[14] ^ io_D;	// src/main/scala/AdderSubtractor.scala:33:{17,21}
  assign io_S =
    {io_B[15] ^ io_D ^ io_A[15] ^ (b_14 & io_A[14] | C_vec_14 & (b_14 ^ io_A[14])),
     b_14 ^ io_A[14] ^ C_vec_14,
     b_13 ^ io_A[13] ^ C_vec_13,
     b_12 ^ io_A[12] ^ C_vec_12,
     b_11 ^ io_A[11] ^ C_vec_11,
     b_10 ^ io_A[10] ^ C_vec_10,
     b_9 ^ io_A[9] ^ C_vec_9,
     b_8 ^ io_A[8] ^ C_vec_8,
     b_7 ^ io_A[7] ^ C_vec_7,
     b_6 ^ io_A[6] ^ C_vec_6,
     b_5 ^ io_A[5] ^ C_vec_5,
     b_4 ^ io_A[4] ^ C_vec_4,
     b_3 ^ io_A[3] ^ C_vec_3,
     b_2 ^ io_A[2] ^ C_vec_2,
     b_1 ^ io_A[1] ^ C_vec_1,
     b ^ io_A[0] ^ io_D};	// <stdin>:212:3, :448:3, :684:3, :920:3, :1156:3, :1392:3, :1628:3, :1864:3, :2100:3, :2336:3, :2572:3, :2808:3, :3044:3, :3280:3, :3516:3, :3752:3, :3988:3, :4224:3, :4460:3, :4696:3, :4932:3, :5168:3, :5404:3, :5640:3, :5876:3, :6112:3, :6348:3, :6584:3, :6820:3, :7056:3, :7292:3, :7528:3, :7764:3, :8000:3, :8236:3, :8472:3, :8708:3, :8944:3, :9180:3, :9416:3, :9652:3, :9888:3, :10124:3, :10360:3, :10596:3, :10832:3, :11068:3, :11304:3, src/main/scala/AdderSubtractor.scala:33:{17,21}, :34:{29,33}, :35:{24,35,47,52}, :38:25
endmodule

module CordicCore(	// <stdin>:11540:3
  input         clock,	// <stdin>:11541:11
                reset,	// <stdin>:11542:11
                io_in_valid,	// src/main/scala/CordicCore.scala:23:14
  input  [15:0] io_in_bits_cordic_x,	// src/main/scala/CordicCore.scala:23:14
                io_in_bits_cordic_y,	// src/main/scala/CordicCore.scala:23:14
                io_in_bits_cordic_z,	// src/main/scala/CordicCore.scala:23:14
  input         io_in_bits_control_rotType,	// src/main/scala/CordicCore.scala:23:14
                io_in_bits_control_mode,	// src/main/scala/CordicCore.scala:23:14
  input  [4:0]  io_in_bits_control_op,	// src/main/scala/CordicCore.scala:23:14
  input  [3:0]  io_in_bits_control_xOpSpecific,	// src/main/scala/CordicCore.scala:23:14
                io_in_bits_control_yOpSpecific,	// src/main/scala/CordicCore.scala:23:14
  output        io_out_valid,	// src/main/scala/CordicCore.scala:23:14
  output [15:0] io_out_bits_cordic_x,	// src/main/scala/CordicCore.scala:23:14
                io_out_bits_cordic_y,	// src/main/scala/CordicCore.scala:23:14
                io_out_bits_cordic_z,	// src/main/scala/CordicCore.scala:23:14
  output [4:0]  io_out_bits_control_op,	// src/main/scala/CordicCore.scala:23:14
  output [3:0]  io_out_bits_control_xOpSpecific,	// src/main/scala/CordicCore.scala:23:14
                io_out_bits_control_yOpSpecific	// src/main/scala/CordicCore.scala:23:14
);

  wire [15:0] _adders_15_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_15_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_15_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_14_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_14_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_14_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_13_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_13_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_13_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_12_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_12_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_12_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_11_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_11_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_11_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_10_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_10_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_10_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_9_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_9_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_9_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_8_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_8_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_8_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_7_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_7_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_7_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_6_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_6_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_6_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_5_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_5_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_5_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_4_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_4_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_4_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_3_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_3_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_3_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_2_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_2_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_2_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_1_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_1_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_1_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_0_2_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_0_1_io_S;	// src/main/scala/CordicCore.scala:44:60
  wire [15:0] _adders_0_0_io_S;	// src/main/scala/CordicCore.scala:44:60
  reg  [15:0] inRegs_cordic_x;	// src/main/scala/CordicCore.scala:40:29
  reg  [15:0] inRegs_cordic_y;	// src/main/scala/CordicCore.scala:40:29
  reg  [15:0] inRegs_cordic_z;	// src/main/scala/CordicCore.scala:40:29
  reg         inRegs_control_rotType;	// src/main/scala/CordicCore.scala:40:29
  reg         inRegs_control_mode;	// src/main/scala/CordicCore.scala:40:29
  reg  [4:0]  inRegs_control_op;	// src/main/scala/CordicCore.scala:40:29
  reg  [3:0]  inRegs_control_xOpSpecific;	// src/main/scala/CordicCore.scala:40:29
  reg  [3:0]  inRegs_control_yOpSpecific;	// src/main/scala/CordicCore.scala:40:29
  reg         inValidReg;	// src/main/scala/CordicCore.scala:41:27
  reg  [15:0] pipelineRegs_0_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_0_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_0_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_0_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_0_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_0_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_0_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_0_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_1_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_1_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_1_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_1_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_1_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_1_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_1_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_1_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_2_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_2_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_2_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_2_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_2_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_2_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_2_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_2_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_3_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_3_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_3_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_3_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_3_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_3_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_3_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_3_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_4_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_4_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_4_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_4_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_4_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_4_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_4_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_4_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_5_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_5_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_5_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_5_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_5_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_5_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_5_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_5_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_6_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_6_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_6_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_6_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_6_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_6_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_6_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_6_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_7_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_7_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_7_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_7_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_7_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_7_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_7_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_7_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_8_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_8_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_8_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_8_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_8_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_8_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_8_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_8_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_9_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_9_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_9_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_9_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_9_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_9_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_9_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_9_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_10_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_10_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_10_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_10_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_10_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_10_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_10_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_10_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_11_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_11_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_11_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_11_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_11_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_11_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_11_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_11_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_12_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_12_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_12_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_12_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_12_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_12_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_12_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_12_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_13_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_13_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_13_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_13_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_13_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_13_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_13_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_13_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_14_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_14_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_14_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_14_control_rotType;	// src/main/scala/CordicCore.scala:48:66
  reg         pipelineRegs_14_control_mode;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_14_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_14_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_14_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_15_cordic_x;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_15_cordic_y;	// src/main/scala/CordicCore.scala:48:66
  reg  [15:0] pipelineRegs_15_cordic_z;	// src/main/scala/CordicCore.scala:48:66
  reg  [4:0]  pipelineRegs_15_control_op;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_15_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg  [3:0]  pipelineRegs_15_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
  reg         validRegs_0;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_1;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_2;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_3;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_4;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_5;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_6;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_7;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_8;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_9;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_10;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_11;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_12;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_13;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_14;	// src/main/scala/CordicCore.scala:49:64
  reg         validRegs_15;	// src/main/scala/CordicCore.scala:49:64
  wire        sigma =
    inRegs_control_mode
      ? $signed(inRegs_cordic_y) < 16'sh0
      : $signed(inRegs_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:40:29, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [12:0] _adders_0_2_io_B_T_1 = inRegs_control_rotType ? 13'h1FFF : 13'hC90;	// src/main/scala/CordicCore.scala:40:29, :117:29
  wire        sigma_1 =
    pipelineRegs_0_control_mode
      ? $signed(pipelineRegs_0_cordic_y) < 16'sh0
      : $signed(pipelineRegs_0_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [12:0] _adders_1_2_io_B_T_1 = pipelineRegs_0_control_rotType ? 13'h8C9 : 13'h76B;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_2 =
    pipelineRegs_1_control_mode
      ? $signed(pipelineRegs_1_cordic_y) < 16'sh0
      : $signed(pipelineRegs_1_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [11:0] _adders_2_2_io_B_T_1 = pipelineRegs_1_control_rotType ? 12'h416 : 12'h3EB;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_3 =
    pipelineRegs_2_control_mode
      ? $signed(pipelineRegs_2_cordic_y) < 16'sh0
      : $signed(pipelineRegs_2_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [10:0] _adders_3_2_io_B_T_1 = pipelineRegs_2_control_rotType ? 11'h202 : 11'h1FD;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_4 =
    pipelineRegs_3_control_mode
      ? $signed(pipelineRegs_3_cordic_y) < 16'sh0
      : $signed(pipelineRegs_3_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [9:0]  _adders_4_2_io_B_T_1 = pipelineRegs_3_control_rotType ? 10'h100 : 10'hFF;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_5 =
    pipelineRegs_4_control_mode
      ? $signed(pipelineRegs_4_cordic_y) < 16'sh0
      : $signed(pipelineRegs_4_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [9:0]  _adders_5_2_io_B_T_1 = pipelineRegs_4_control_rotType ? 10'h100 : 10'hFF;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_6 =
    pipelineRegs_5_control_mode
      ? $signed(pipelineRegs_5_cordic_y) < 16'sh0
      : $signed(pipelineRegs_5_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [8:0]  _adders_6_2_io_B_T_1 = pipelineRegs_5_control_rotType ? 9'h80 : 9'h7F;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_7 =
    pipelineRegs_6_control_mode
      ? $signed(pipelineRegs_6_cordic_y) < 16'sh0
      : $signed(pipelineRegs_6_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [7:0]  _adders_7_2_io_B_T_1 = pipelineRegs_6_control_rotType ? 8'h40 : 8'h3F;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_8 =
    pipelineRegs_7_control_mode
      ? $signed(pipelineRegs_7_cordic_y) < 16'sh0
      : $signed(pipelineRegs_7_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [6:0]  _adders_8_2_io_B_T_1 = pipelineRegs_7_control_rotType ? 7'h20 : 7'h1F;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_9 =
    pipelineRegs_8_control_mode
      ? $signed(pipelineRegs_8_cordic_y) < 16'sh0
      : $signed(pipelineRegs_8_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [5:0]  _adders_9_2_io_B_T_1 = pipelineRegs_8_control_rotType ? 6'h10 : 6'hF;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_10 =
    pipelineRegs_9_control_mode
      ? $signed(pipelineRegs_9_cordic_y) < 16'sh0
      : $signed(pipelineRegs_9_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [4:0]  _adders_10_2_io_B_T_1 = pipelineRegs_9_control_rotType ? 5'h8 : 5'h7;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_11 =
    pipelineRegs_10_control_mode
      ? $signed(pipelineRegs_10_cordic_y) < 16'sh0
      : $signed(pipelineRegs_10_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [3:0]  _adders_11_2_io_B_T_1 = pipelineRegs_10_control_rotType ? 4'h4 : 4'h3;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_12 =
    pipelineRegs_11_control_mode
      ? $signed(pipelineRegs_11_cordic_y) < 16'sh0
      : $signed(pipelineRegs_11_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire [2:0]  _adders_12_2_io_B_T_1 = pipelineRegs_11_control_rotType ? 3'h2 : 3'h1;	// src/main/scala/CordicCore.scala:48:66, :117:29
  wire        sigma_13 =
    pipelineRegs_12_control_mode
      ? $signed(pipelineRegs_12_cordic_y) < 16'sh0
      : $signed(pipelineRegs_12_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire        sigma_14 =
    pipelineRegs_13_control_mode
      ? $signed(pipelineRegs_13_cordic_y) < 16'sh0
      : $signed(pipelineRegs_13_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  wire        sigma_15 =
    pipelineRegs_14_control_mode
      ? $signed(pipelineRegs_14_cordic_y) < 16'sh0
      : $signed(pipelineRegs_14_cordic_z) > -16'sh1;	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:{13,41}, :71:{13,41}, :107:15
  always @(posedge clock) begin	// <stdin>:11541:11
    if (io_in_valid) begin	// src/main/scala/CordicCore.scala:23:14
      inRegs_cordic_x <= io_in_bits_cordic_x;	// src/main/scala/CordicCore.scala:40:29
      inRegs_cordic_y <= io_in_bits_cordic_y;	// src/main/scala/CordicCore.scala:40:29
      inRegs_cordic_z <= io_in_bits_cordic_z;	// src/main/scala/CordicCore.scala:40:29
      inRegs_control_rotType <= io_in_bits_control_rotType;	// src/main/scala/CordicCore.scala:40:29
      inRegs_control_mode <= io_in_bits_control_mode;	// src/main/scala/CordicCore.scala:40:29
      inRegs_control_op <= io_in_bits_control_op;	// src/main/scala/CordicCore.scala:40:29
      inRegs_control_xOpSpecific <= io_in_bits_control_xOpSpecific;	// src/main/scala/CordicCore.scala:40:29
      inRegs_control_yOpSpecific <= io_in_bits_control_yOpSpecific;	// src/main/scala/CordicCore.scala:40:29
    end
    if (inValidReg) begin	// src/main/scala/CordicCore.scala:41:27
      pipelineRegs_0_cordic_x <=
        inRegs_control_rotType ? inRegs_cordic_x : _adders_0_0_io_S;	// src/main/scala/CordicCore.scala:40:29, :44:60, :48:66, :120:18, :121:19, :123:33
      pipelineRegs_0_cordic_y <=
        inRegs_control_rotType ? inRegs_cordic_y : _adders_0_1_io_S;	// src/main/scala/CordicCore.scala:40:29, :44:60, :48:66, :120:18, :121:19, :124:33
      pipelineRegs_0_cordic_z <=
        inRegs_control_rotType ? inRegs_cordic_z : _adders_0_2_io_S;	// src/main/scala/CordicCore.scala:40:29, :44:60, :48:66, :120:18, :121:19, :125:33
      pipelineRegs_0_control_rotType <= inRegs_control_rotType;	// src/main/scala/CordicCore.scala:40:29, :48:66
      pipelineRegs_0_control_mode <= inRegs_control_mode;	// src/main/scala/CordicCore.scala:40:29, :48:66
      pipelineRegs_0_control_op <= inRegs_control_op;	// src/main/scala/CordicCore.scala:40:29, :48:66
      pipelineRegs_0_control_xOpSpecific <= inRegs_control_xOpSpecific;	// src/main/scala/CordicCore.scala:40:29, :48:66
      pipelineRegs_0_control_yOpSpecific <= inRegs_control_yOpSpecific;	// src/main/scala/CordicCore.scala:40:29, :48:66
    end
    if (validRegs_0) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_1_cordic_x <= _adders_1_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_1_cordic_y <= _adders_1_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_1_cordic_z <= _adders_1_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_1_control_rotType <= pipelineRegs_0_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_1_control_mode <= pipelineRegs_0_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_1_control_op <= pipelineRegs_0_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_1_control_xOpSpecific <= pipelineRegs_0_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_1_control_yOpSpecific <= pipelineRegs_0_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_1) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_2_cordic_x <= _adders_2_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_2_cordic_y <= _adders_2_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_2_cordic_z <= _adders_2_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_2_control_rotType <= pipelineRegs_1_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_2_control_mode <= pipelineRegs_1_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_2_control_op <= pipelineRegs_1_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_2_control_xOpSpecific <= pipelineRegs_1_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_2_control_yOpSpecific <= pipelineRegs_1_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_2) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_3_cordic_x <= _adders_3_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_3_cordic_y <= _adders_3_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_3_cordic_z <= _adders_3_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_3_control_rotType <= pipelineRegs_2_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_3_control_mode <= pipelineRegs_2_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_3_control_op <= pipelineRegs_2_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_3_control_xOpSpecific <= pipelineRegs_2_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_3_control_yOpSpecific <= pipelineRegs_2_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_3) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_4_cordic_x <= _adders_4_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_4_cordic_y <= _adders_4_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_4_cordic_z <= _adders_4_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_4_control_rotType <= pipelineRegs_3_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_4_control_mode <= pipelineRegs_3_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_4_control_op <= pipelineRegs_3_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_4_control_xOpSpecific <= pipelineRegs_3_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_4_control_yOpSpecific <= pipelineRegs_3_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_4) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_5_cordic_x <= _adders_5_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_5_cordic_y <= _adders_5_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_5_cordic_z <= _adders_5_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_5_control_rotType <= pipelineRegs_4_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_5_control_mode <= pipelineRegs_4_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_5_control_op <= pipelineRegs_4_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_5_control_xOpSpecific <= pipelineRegs_4_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_5_control_yOpSpecific <= pipelineRegs_4_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_5) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_6_cordic_x <= _adders_6_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_6_cordic_y <= _adders_6_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_6_cordic_z <= _adders_6_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_6_control_rotType <= pipelineRegs_5_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_6_control_mode <= pipelineRegs_5_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_6_control_op <= pipelineRegs_5_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_6_control_xOpSpecific <= pipelineRegs_5_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_6_control_yOpSpecific <= pipelineRegs_5_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_6) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_7_cordic_x <= _adders_7_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_7_cordic_y <= _adders_7_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_7_cordic_z <= _adders_7_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_7_control_rotType <= pipelineRegs_6_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_7_control_mode <= pipelineRegs_6_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_7_control_op <= pipelineRegs_6_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_7_control_xOpSpecific <= pipelineRegs_6_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_7_control_yOpSpecific <= pipelineRegs_6_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_7) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_8_cordic_x <= _adders_8_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_8_cordic_y <= _adders_8_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_8_cordic_z <= _adders_8_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_8_control_rotType <= pipelineRegs_7_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_8_control_mode <= pipelineRegs_7_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_8_control_op <= pipelineRegs_7_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_8_control_xOpSpecific <= pipelineRegs_7_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_8_control_yOpSpecific <= pipelineRegs_7_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_8) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_9_cordic_x <= _adders_9_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_9_cordic_y <= _adders_9_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_9_cordic_z <= _adders_9_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_9_control_rotType <= pipelineRegs_8_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_9_control_mode <= pipelineRegs_8_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_9_control_op <= pipelineRegs_8_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_9_control_xOpSpecific <= pipelineRegs_8_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_9_control_yOpSpecific <= pipelineRegs_8_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_9) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_10_cordic_x <= _adders_10_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_10_cordic_y <= _adders_10_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_10_cordic_z <= _adders_10_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_10_control_rotType <= pipelineRegs_9_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_10_control_mode <= pipelineRegs_9_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_10_control_op <= pipelineRegs_9_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_10_control_xOpSpecific <= pipelineRegs_9_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_10_control_yOpSpecific <= pipelineRegs_9_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_10) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_11_cordic_x <= _adders_11_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_11_cordic_y <= _adders_11_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_11_cordic_z <= _adders_11_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_11_control_rotType <= pipelineRegs_10_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_11_control_mode <= pipelineRegs_10_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_11_control_op <= pipelineRegs_10_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_11_control_xOpSpecific <= pipelineRegs_10_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_11_control_yOpSpecific <= pipelineRegs_10_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_11) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_12_cordic_x <= _adders_12_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_12_cordic_y <= _adders_12_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_12_cordic_z <= _adders_12_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_12_control_rotType <= pipelineRegs_11_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_12_control_mode <= pipelineRegs_11_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_12_control_op <= pipelineRegs_11_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_12_control_xOpSpecific <= pipelineRegs_11_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_12_control_yOpSpecific <= pipelineRegs_11_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_12) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_13_cordic_x <= _adders_13_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_13_cordic_y <= _adders_13_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_13_cordic_z <= _adders_13_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_13_control_rotType <= pipelineRegs_12_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_13_control_mode <= pipelineRegs_12_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_13_control_op <= pipelineRegs_12_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_13_control_xOpSpecific <= pipelineRegs_12_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_13_control_yOpSpecific <= pipelineRegs_12_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_13) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_14_cordic_x <= _adders_14_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_14_cordic_y <= _adders_14_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_14_cordic_z <= _adders_14_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_14_control_rotType <= pipelineRegs_13_control_rotType;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_14_control_mode <= pipelineRegs_13_control_mode;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_14_control_op <= pipelineRegs_13_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_14_control_xOpSpecific <= pipelineRegs_13_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_14_control_yOpSpecific <= pipelineRegs_13_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (validRegs_14) begin	// src/main/scala/CordicCore.scala:49:64
      pipelineRegs_15_cordic_x <= _adders_15_0_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_15_cordic_y <= _adders_15_1_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_15_cordic_z <= _adders_15_2_io_S;	// src/main/scala/CordicCore.scala:44:60, :48:66
      pipelineRegs_15_control_op <= pipelineRegs_14_control_op;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_15_control_xOpSpecific <= pipelineRegs_14_control_xOpSpecific;	// src/main/scala/CordicCore.scala:48:66
      pipelineRegs_15_control_yOpSpecific <= pipelineRegs_14_control_yOpSpecific;	// src/main/scala/CordicCore.scala:48:66
    end
    if (reset) begin	// <stdin>:11541:11
      inValidReg <= 1'h0;	// src/main/scala/CordicCore.scala:41:27, :69:41
      validRegs_0 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_1 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_2 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_3 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_4 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_5 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_6 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_7 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_8 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_9 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_10 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_11 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_12 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_13 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_14 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
      validRegs_15 <= 1'h0;	// src/main/scala/CordicCore.scala:49:64, :69:41
    end
    else begin	// <stdin>:11541:11
      inValidReg <= io_in_valid;	// src/main/scala/CordicCore.scala:41:27
      validRegs_0 <= inValidReg;	// src/main/scala/CordicCore.scala:41:27, :49:64
      validRegs_1 <= validRegs_0;	// src/main/scala/CordicCore.scala:49:64
      validRegs_2 <= validRegs_1;	// src/main/scala/CordicCore.scala:49:64
      validRegs_3 <= validRegs_2;	// src/main/scala/CordicCore.scala:49:64
      validRegs_4 <= validRegs_3;	// src/main/scala/CordicCore.scala:49:64
      validRegs_5 <= validRegs_4;	// src/main/scala/CordicCore.scala:49:64
      validRegs_6 <= validRegs_5;	// src/main/scala/CordicCore.scala:49:64
      validRegs_7 <= validRegs_6;	// src/main/scala/CordicCore.scala:49:64
      validRegs_8 <= validRegs_7;	// src/main/scala/CordicCore.scala:49:64
      validRegs_9 <= validRegs_8;	// src/main/scala/CordicCore.scala:49:64
      validRegs_10 <= validRegs_9;	// src/main/scala/CordicCore.scala:49:64
      validRegs_11 <= validRegs_10;	// src/main/scala/CordicCore.scala:49:64
      validRegs_12 <= validRegs_11;	// src/main/scala/CordicCore.scala:49:64
      validRegs_13 <= validRegs_12;	// src/main/scala/CordicCore.scala:49:64
      validRegs_14 <= validRegs_13;	// src/main/scala/CordicCore.scala:49:64
      validRegs_15 <= validRegs_14;	// src/main/scala/CordicCore.scala:49:64
    end
  end // always @(posedge)
  AdderSubtractor adders_0_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (inRegs_cordic_x),	// src/main/scala/CordicCore.scala:40:29
    .io_B (inRegs_cordic_y),	// src/main/scala/CordicCore.scala:40:29
    .io_D (inRegs_control_rotType ^ sigma),	// src/main/scala/CordicCore.scala:40:29, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_0_0_io_S)
  );
  AdderSubtractor adders_0_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (inRegs_cordic_y),	// src/main/scala/CordicCore.scala:40:29
    .io_B (inRegs_cordic_x),	// src/main/scala/CordicCore.scala:40:29
    .io_D (~sigma),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_0_1_io_S)
  );
  AdderSubtractor adders_0_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (inRegs_cordic_z),	// src/main/scala/CordicCore.scala:40:29
    .io_B ({{3{_adders_0_2_io_B_T_1[12]}}, _adders_0_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_0_2_io_S)
  );
  AdderSubtractor adders_1_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_0_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({pipelineRegs_0_cordic_y[15], pipelineRegs_0_cordic_y[15:1]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_0_control_rotType ^ sigma_1),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_1_0_io_S)
  );
  AdderSubtractor adders_1_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_0_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({pipelineRegs_0_cordic_x[15], pipelineRegs_0_cordic_x[15:1]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_1),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_1_1_io_S)
  );
  AdderSubtractor adders_1_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_0_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{3{_adders_1_2_io_B_T_1[12]}}, _adders_1_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_1),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_1_2_io_S)
  );
  AdderSubtractor adders_2_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_1_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{2{pipelineRegs_1_cordic_y[15]}}, pipelineRegs_1_cordic_y[15:2]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_1_control_rotType ^ sigma_2),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_2_0_io_S)
  );
  AdderSubtractor adders_2_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_1_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{2{pipelineRegs_1_cordic_x[15]}}, pipelineRegs_1_cordic_x[15:2]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_2),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_2_1_io_S)
  );
  AdderSubtractor adders_2_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_1_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{4{_adders_2_2_io_B_T_1[11]}}, _adders_2_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_2),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_2_2_io_S)
  );
  AdderSubtractor adders_3_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_2_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{3{pipelineRegs_2_cordic_y[15]}}, pipelineRegs_2_cordic_y[15:3]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_2_control_rotType ^ sigma_3),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_3_0_io_S)
  );
  AdderSubtractor adders_3_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_2_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{3{pipelineRegs_2_cordic_x[15]}}, pipelineRegs_2_cordic_x[15:3]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_3),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_3_1_io_S)
  );
  AdderSubtractor adders_3_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_2_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{5{_adders_3_2_io_B_T_1[10]}}, _adders_3_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_3),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_3_2_io_S)
  );
  AdderSubtractor adders_4_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_3_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{4{pipelineRegs_3_cordic_y[15]}}, pipelineRegs_3_cordic_y[15:4]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_3_control_rotType ^ sigma_4),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_4_0_io_S)
  );
  AdderSubtractor adders_4_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_3_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{4{pipelineRegs_3_cordic_x[15]}}, pipelineRegs_3_cordic_x[15:4]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_4),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_4_1_io_S)
  );
  AdderSubtractor adders_4_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_3_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{6{_adders_4_2_io_B_T_1[9]}}, _adders_4_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_4),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_4_2_io_S)
  );
  AdderSubtractor adders_5_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_4_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{4{pipelineRegs_4_cordic_y[15]}}, pipelineRegs_4_cordic_y[15:4]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_4_control_rotType ^ sigma_5),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_5_0_io_S)
  );
  AdderSubtractor adders_5_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_4_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{4{pipelineRegs_4_cordic_x[15]}}, pipelineRegs_4_cordic_x[15:4]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_5),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_5_1_io_S)
  );
  AdderSubtractor adders_5_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_4_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{6{_adders_5_2_io_B_T_1[9]}}, _adders_5_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_5),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_5_2_io_S)
  );
  AdderSubtractor adders_6_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_5_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{5{pipelineRegs_5_cordic_y[15]}}, pipelineRegs_5_cordic_y[15:5]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_5_control_rotType ^ sigma_6),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_6_0_io_S)
  );
  AdderSubtractor adders_6_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_5_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{5{pipelineRegs_5_cordic_x[15]}}, pipelineRegs_5_cordic_x[15:5]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_6),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_6_1_io_S)
  );
  AdderSubtractor adders_6_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_5_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{7{_adders_6_2_io_B_T_1[8]}}, _adders_6_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_6),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_6_2_io_S)
  );
  AdderSubtractor adders_7_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_6_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{6{pipelineRegs_6_cordic_y[15]}}, pipelineRegs_6_cordic_y[15:6]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_6_control_rotType ^ sigma_7),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_7_0_io_S)
  );
  AdderSubtractor adders_7_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_6_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{6{pipelineRegs_6_cordic_x[15]}}, pipelineRegs_6_cordic_x[15:6]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_7),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_7_1_io_S)
  );
  AdderSubtractor adders_7_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_6_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{8{_adders_7_2_io_B_T_1[7]}}, _adders_7_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_7),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_7_2_io_S)
  );
  AdderSubtractor adders_8_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_7_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{7{pipelineRegs_7_cordic_y[15]}}, pipelineRegs_7_cordic_y[15:7]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_7_control_rotType ^ sigma_8),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_8_0_io_S)
  );
  AdderSubtractor adders_8_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_7_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{7{pipelineRegs_7_cordic_x[15]}}, pipelineRegs_7_cordic_x[15:7]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_8),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_8_1_io_S)
  );
  AdderSubtractor adders_8_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_7_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{9{_adders_8_2_io_B_T_1[6]}}, _adders_8_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_8),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_8_2_io_S)
  );
  AdderSubtractor adders_9_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_8_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{8{pipelineRegs_8_cordic_y[15]}}, pipelineRegs_8_cordic_y[15:8]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_8_control_rotType ^ sigma_9),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_9_0_io_S)
  );
  AdderSubtractor adders_9_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_8_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{8{pipelineRegs_8_cordic_x[15]}}, pipelineRegs_8_cordic_x[15:8]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_9),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_9_1_io_S)
  );
  AdderSubtractor adders_9_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_8_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{10{_adders_9_2_io_B_T_1[5]}}, _adders_9_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_9),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_9_2_io_S)
  );
  AdderSubtractor adders_10_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_9_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{9{pipelineRegs_9_cordic_y[15]}}, pipelineRegs_9_cordic_y[15:9]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_9_control_rotType ^ sigma_10),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_10_0_io_S)
  );
  AdderSubtractor adders_10_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_9_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{9{pipelineRegs_9_cordic_x[15]}}, pipelineRegs_9_cordic_x[15:9]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_10),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_10_1_io_S)
  );
  AdderSubtractor adders_10_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_9_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{11{_adders_10_2_io_B_T_1[4]}}, _adders_10_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_10),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_10_2_io_S)
  );
  AdderSubtractor adders_11_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_10_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{10{pipelineRegs_10_cordic_y[15]}}, pipelineRegs_10_cordic_y[15:10]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_10_control_rotType ^ sigma_11),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_11_0_io_S)
  );
  AdderSubtractor adders_11_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_10_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{10{pipelineRegs_10_cordic_x[15]}}, pipelineRegs_10_cordic_x[15:10]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_11),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_11_1_io_S)
  );
  AdderSubtractor adders_11_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_10_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{12{_adders_11_2_io_B_T_1[3]}}, _adders_11_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_11),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_11_2_io_S)
  );
  AdderSubtractor adders_12_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_11_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{11{pipelineRegs_11_cordic_y[15]}}, pipelineRegs_11_cordic_y[15:11]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_11_control_rotType ^ sigma_12),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_12_0_io_S)
  );
  AdderSubtractor adders_12_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_11_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{11{pipelineRegs_11_cordic_x[15]}}, pipelineRegs_11_cordic_x[15:11]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_12),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_12_1_io_S)
  );
  AdderSubtractor adders_12_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_11_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{13{_adders_12_2_io_B_T_1[2]}}, _adders_12_2_io_B_T_1}),	// src/main/scala/CordicCore.scala:117:{23,29}
    .io_D (sigma_12),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_12_2_io_S)
  );
  AdderSubtractor adders_13_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_12_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{12{pipelineRegs_12_cordic_y[15]}}, pipelineRegs_12_cordic_y[15:12]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_12_control_rotType ^ sigma_13),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_13_0_io_S)
  );
  AdderSubtractor adders_13_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_12_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{12{pipelineRegs_12_cordic_x[15]}}, pipelineRegs_12_cordic_x[15:12]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_13),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_13_1_io_S)
  );
  AdderSubtractor adders_13_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_12_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({15'h0, pipelineRegs_12_control_rotType}),	// src/main/scala/CordicCore.scala:48:66, :117:23
    .io_D (sigma_13),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_13_2_io_S)
  );
  AdderSubtractor adders_14_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_13_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{13{pipelineRegs_13_cordic_y[15]}}, pipelineRegs_13_cordic_y[15:13]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_13_control_rotType ^ sigma_14),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_14_0_io_S)
  );
  AdderSubtractor adders_14_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_13_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{13{pipelineRegs_13_cordic_x[15]}}, pipelineRegs_13_cordic_x[15:13]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_14),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_14_1_io_S)
  );
  AdderSubtractor adders_14_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_13_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B (16'h0),	// src/main/scala/CordicCore.scala:107:15
    .io_D (sigma_14),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_14_2_io_S)
  );
  AdderSubtractor adders_15_0 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_14_cordic_x),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{13{pipelineRegs_14_cordic_y[15]}}, pipelineRegs_14_cordic_y[15:13]}),	// src/main/scala/CordicCore.scala:48:66, :106:{15,43}
    .io_D (pipelineRegs_14_control_rotType ^ sigma_15),	// src/main/scala/CordicCore.scala:48:66, :68:64, :69:13, :71:13, :100:19
    .io_S (_adders_15_0_io_S)
  );
  AdderSubtractor adders_15_1 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_14_cordic_y),	// src/main/scala/CordicCore.scala:48:66
    .io_B ({{13{pipelineRegs_14_cordic_x[15]}}, pipelineRegs_14_cordic_x[15:13]}),	// src/main/scala/CordicCore.scala:48:66, :105:{15,43}
    .io_D (~sigma_15),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13, :101:19
    .io_S (_adders_15_1_io_S)
  );
  AdderSubtractor adders_15_2 (	// src/main/scala/CordicCore.scala:44:60
    .io_A (pipelineRegs_14_cordic_z),	// src/main/scala/CordicCore.scala:48:66
    .io_B (16'h0),	// src/main/scala/CordicCore.scala:107:15
    .io_D (sigma_15),	// src/main/scala/CordicCore.scala:68:64, :69:13, :71:13
    .io_S (_adders_15_2_io_S)
  );
  assign io_out_valid = validRegs_15;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:49:64
  assign io_out_bits_cordic_x = pipelineRegs_15_cordic_x;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
  assign io_out_bits_cordic_y = pipelineRegs_15_cordic_y;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
  assign io_out_bits_cordic_z = pipelineRegs_15_cordic_z;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
  assign io_out_bits_control_op = pipelineRegs_15_control_op;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
  assign io_out_bits_control_xOpSpecific = pipelineRegs_15_control_xOpSpecific;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
  assign io_out_bits_control_yOpSpecific = pipelineRegs_15_control_yOpSpecific;	// <stdin>:11540:3, src/main/scala/CordicCore.scala:48:66
endmodule

module CordicAccelerator(	// <stdin>:12934:3
  input         clock,	// <stdin>:12935:11
                reset,	// <stdin>:12936:11
                io_in_valid,	// src/main/scala/CordicAccelerator.scala:32:14
  input  [15:0] io_in_bits_rs1,	// src/main/scala/CordicAccelerator.scala:32:14
                io_in_bits_rs2,	// src/main/scala/CordicAccelerator.scala:32:14
                io_in_bits_rs3,	// src/main/scala/CordicAccelerator.scala:32:14
  input  [4:0]  io_in_bits_op,	// src/main/scala/CordicAccelerator.scala:32:14
  output        io_out_valid,	// src/main/scala/CordicAccelerator.scala:32:14
  output [15:0] io_out_bits_cordic_x,	// src/main/scala/CordicAccelerator.scala:32:14
                io_out_bits_cordic_y,	// src/main/scala/CordicAccelerator.scala:32:14
                io_out_bits_cordic_z,	// src/main/scala/CordicAccelerator.scala:32:14
                io_out_bits_dOut	// src/main/scala/CordicAccelerator.scala:32:14
);

  wire [15:0] _cordicCore_io_out_bits_cordic_x;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [15:0] _cordicCore_io_out_bits_cordic_y;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [15:0] _cordicCore_io_out_bits_cordic_z;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [4:0]  _cordicCore_io_out_bits_control_op;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [3:0]  _cordicCore_io_out_bits_control_xOpSpecific;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [3:0]  _cordicCore_io_out_bits_control_yOpSpecific;	// src/main/scala/CordicAccelerator.scala:36:29
  wire [15:0] _preprocessor_io_out_cordic_x;	// src/main/scala/CordicAccelerator.scala:34:29
  wire [15:0] _preprocessor_io_out_cordic_y;	// src/main/scala/CordicAccelerator.scala:34:29
  wire [15:0] _preprocessor_io_out_cordic_z;	// src/main/scala/CordicAccelerator.scala:34:29
  wire        _preprocessor_io_out_control_rotType;	// src/main/scala/CordicAccelerator.scala:34:29
  wire        _preprocessor_io_out_control_mode;	// src/main/scala/CordicAccelerator.scala:34:29
  wire [4:0]  _preprocessor_io_out_control_op;	// src/main/scala/CordicAccelerator.scala:34:29
  wire [3:0]  _preprocessor_io_out_control_xOpSpecific;	// src/main/scala/CordicAccelerator.scala:34:29
  wire [3:0]  _preprocessor_io_out_control_yOpSpecific;	// src/main/scala/CordicAccelerator.scala:34:29
  CordicPreprocessor preprocessor (	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_rs1                  (io_in_bits_rs1),
    .io_in_op                   (io_in_bits_op),
    .io_out_cordic_x            (_preprocessor_io_out_cordic_x),
    .io_out_cordic_y            (_preprocessor_io_out_cordic_y),
    .io_out_cordic_z            (_preprocessor_io_out_cordic_z),
    .io_out_control_rotType     (_preprocessor_io_out_control_rotType),
    .io_out_control_mode        (_preprocessor_io_out_control_mode),
    .io_out_control_op          (_preprocessor_io_out_control_op),
    .io_out_control_xOpSpecific (_preprocessor_io_out_control_xOpSpecific),
    .io_out_control_yOpSpecific (_preprocessor_io_out_control_yOpSpecific)
  );
  CordicPostprocessor postprocessor (	// src/main/scala/CordicAccelerator.scala:35:29
    .io_in_cordic_x            (_cordicCore_io_out_bits_cordic_x),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_in_cordic_y            (_cordicCore_io_out_bits_cordic_y),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_in_cordic_z            (_cordicCore_io_out_bits_cordic_z),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_in_control_op          (_cordicCore_io_out_bits_control_op),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_in_control_xOpSpecific (_cordicCore_io_out_bits_control_xOpSpecific),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_in_control_yOpSpecific (_cordicCore_io_out_bits_control_yOpSpecific),	// src/main/scala/CordicAccelerator.scala:36:29
    .io_out_cordic_x           (io_out_bits_cordic_x),
    .io_out_cordic_y           (io_out_bits_cordic_y),
    .io_out_cordic_z           (io_out_bits_cordic_z),
    .io_out_dOut               (io_out_bits_dOut)
  );
  CordicCore cordicCore (	// src/main/scala/CordicAccelerator.scala:36:29
    .clock                           (clock),
    .reset                           (reset),
    .io_in_valid                     (io_in_valid),
    .io_in_bits_cordic_x             (_preprocessor_io_out_cordic_x),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_cordic_y             (_preprocessor_io_out_cordic_y),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_cordic_z             (_preprocessor_io_out_cordic_z),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_control_rotType      (_preprocessor_io_out_control_rotType),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_control_mode         (_preprocessor_io_out_control_mode),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_control_op           (_preprocessor_io_out_control_op),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_control_xOpSpecific  (_preprocessor_io_out_control_xOpSpecific),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_in_bits_control_yOpSpecific  (_preprocessor_io_out_control_yOpSpecific),	// src/main/scala/CordicAccelerator.scala:34:29
    .io_out_valid                    (io_out_valid),
    .io_out_bits_cordic_x            (_cordicCore_io_out_bits_cordic_x),
    .io_out_bits_cordic_y            (_cordicCore_io_out_bits_cordic_y),
    .io_out_bits_cordic_z            (_cordicCore_io_out_bits_cordic_z),
    .io_out_bits_control_op          (_cordicCore_io_out_bits_control_op),
    .io_out_bits_control_xOpSpecific (_cordicCore_io_out_bits_control_xOpSpecific),
    .io_out_bits_control_yOpSpecific (_cordicCore_io_out_bits_control_yOpSpecific)
  );
endmodule

