mantissa-bits: 3
fraction-bits: 13
iterations: 16
preprocessor-class: "UpConvert"
postprocessor-class: "UpConvert"
number-repr: "pi"
enable-circular: true
enable-rotational: true
used-inputs: [1, 2]
up-convert-config:
  use-phase-accum: true
  phase-accum-width: 24